- name: "Deploy WAR on webserver"
  hosts: web
  become: true
  tasks:
  - name: "Copy tomcat-users xml for manager"
    copy:
      src: "{{ playbook_dir }}/../03- Create AddressBook Project/target/addressbook-2.0.war"
      dest: /var/lib/tomcat9/webapps/
  - name: "Restart Tomcat 9"
    systemd:
      name: tomcat9
      state: restarted
