- name: "Install Maven on Provisioning server"
  hosts: localhost
  become: true
  tasks:
  - name: "Update APT Cache"
    apt:
      update_cache: yes
  - name: "Install Maven"
    apt:
      name:
        - maven
      state: present
