- name: "Install Tomcat9 on webserver"
  hosts: web
  become: true
  tasks:
  - name: "Update APT Cache"
    apt:
      update_cache: yes
  - name: "Install Tomcat 9 all"
    apt:
      - name: tomcat9
      - name: tomcat9-admin
      - name: tomcat9-common
      - name: tomcat9-docs
      - name: tomcat9-examples
      - name: tomcat9-user
    state: present
