- name: "Install Tomcat9 on webserver"
  hosts: web
  become: true
  tasks:
  - name: "Update APT Cache"
    apt:
      update_cache: yes
  - name: "Install Tomcat 9 all"
    apt:
      name:
        - tomcat9
        - tomcat9-admin
        - tomcat9-common
        - tomcat9-docs
        - tomcat9-examples
        - tomcat9-user
      state: present
    - name: "Copy tomcat-users xml for manager"
      copy:
        src: {{ playbook_dir }}/tomcat-users.xml
        dest: /var/lib/tomcat9/conf/
    - name: "Restart Tomcat 9"
      systemd:
        name: tomcat9
        state: restarted
