- name: "Install Tomcat9 on webserver"
  hosts: web
  become: true
  tasks:
  - name: "Update APT Cache"
    apt:
      update_cache: yes
  - name: "Install Tomcat 9 all"
    apt:
      name:
        - tomcat9
        - tomcat9-admin
        - tomcat9-common
        - tomcat9-docs
        - tomcat9-examples
        - tomcat9-user
      state: present
